version: 0.2

phases: 
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo "installing something"
            - cd devops-project
            - npm install amazon-cognito-identity-js
    pre_build:
        commands: 
            - echo "we are in the pre build phase"         
            - ls  
            - echo $HOME
            - env
            - echo "UserID:"${COGNITO_ID}
            - echo "ClientID:"$COGNITO_CLIENT_ID
            - echo "API_URL:"$API_URL
            - ls
            - sed -i -e 's/process.env['REACT_APP_.AWS_COGNITO_ID']/'$COGNITO_ID/'g' src/UserPool.js
            - sed -i -e 's/process.env['REACT_APP_.AWS_COGNITO_CLIENT_ID']/'$COGNITO_CLIENT_ID'/g' src/UserPool.js
            - cat src/UserPool.js
            - sed -i -e 's%process.env['REACT_APP_.AWS_API_URL']%'$API_URL'%g' src/components/Lambda.js
            - cat src/components/Lambda.js
            - npm install
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - ls
            - npm run build
    post_build:
        commands:
            - echo "we are in the post build phase"
            - ls
            - cd build
            - ls
            - cat index.html
            - cd ../..
            - ls
artifacts:
  files:
    # - '**/*'
    - 'appspec.yml'
    - 'scripts/*'
    - 'devops-project/build/**/*'

            
